sonar.projectKey=Prueba_DevOps
sonar.projectName=Prueba_DevOps
sonar.sources=web
sonar.host.url=http://sonarqube:9000
sonar.token=sqp_a2552e7afa0e00d562a1c370103a669265b42c3f
sonar.tests=web
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info